# Generated by Django 4.1.5 on 2023-02-23 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_rank', models.IntegerField(default=0, null=True, unique=True)),
                ('collect_name', models.CharField(blank=True, max_length=50, null=True)),
                ('collect_total_est_usd_value', models.CharField(blank=True, max_length=50, null=True)),
                ('collect_volume_24h_usd_value', models.CharField(blank=True, max_length=50, null=True)),
                ('collect_avg_price_24h_usd_value', models.CharField(blank=True, max_length=50, null=True)),
                ('collenct_buy_holder_count', models.CharField(blank=True, max_length=50, null=True)),
                ('collect_buy_holder_usd_value', models.CharField(blank=True, max_length=50, null=True)),
                ('collect_img_url', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('wallet_address', models.CharField(max_length=42, null=True, unique=True, verbose_name='walelt address')),
                ('public_addres', models.CharField(max_length=20, null=True, unique=True, verbose_name='short address')),
                ('wallet_balance_eth', models.DecimalField(decimal_places=5, max_digits=10, null=True, verbose_name='user balance')),
                ('connect_date', models.DateTimeField(auto_now_add=True, verbose_name='user created')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('user_email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='email')),
                ('user_sigh_contact', models.IntegerField(default=0, verbose_name='sigh contract')),
                ('last_collection_update', models.IntegerField(blank=True, default=0, null=True)),
                ('usd_value', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCollectionsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=250, null=True)),
                ('thumbnail_img', models.URLField(max_length=250, null=True)),
                ('collection_name', models.CharField(blank=True, max_length=150, null=True)),
                ('token_name', models.CharField(blank=True, max_length=50, null=True)),
                ('token_id', models.CharField(blank=True, max_length=50, null=True)),
                ('avg_price_24', models.CharField(blank=True, max_length=50, null=True)),
                ('token_usd_price', models.CharField(blank=True, max_length=50, null=True)),
                ('detail_url', models.URLField(max_length=250, null=True)),
                ('collection_logo_url', models.URLField(max_length=250, null=True)),
                ('contract_id', models.CharField(blank=True, max_length=50, null=True)),
                ('inner_id', models.CharField(blank=True, max_length=50, null=True)),
                ('token_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webswap.userprofile')),
            ],
        ),
    ]
